Add LFS locking checks for .uasset and .umap files in repository status
ProjectBorealis/UE4GitPlugin pull request #192
Opened 2024-11-17 03:54 UTC by sanxfxteam

This check provides a helpful warning if git LFS lockable attributes are not detected by the plugin. 
The plugin only checks at the root of the git repo to decide if the repo can support LFS lock.
The check will fail when there is an issue with .gitattributes: if your project in not at the root of the repo or you're using the old content/** configuration from the default plugin.
If the check fails, it will disable git LFS locking, otherwise the plugin has a behavior, believing he can lock files but can't.

2025-01-17 12:46 UTC, mastercoms requested changes
Nice set of changes, this will really help usability! Just one minor change.

2025-01-17 12:46 UTC, mastercoms commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					UE_LOG(LogSourceControl, Warning, TEXT("Git LFS Locking is disabled. Files .uasset or .umap are not lockable. Make sure your .gitattributes is setting lockable attributes for .uasset or .umap at
Can you upgrade this to error if the user has set LFS locking on? I think errors in source control are upgraded in visibility in the UI.

2025-01-17 18:22 UTC, sanxfxteam commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					UE_LOG(LogSourceControl, Warning, TEXT("Git LFS Locking is disabled. Files .uasset or .umap are not lockable. Make sure your .gitattributes is setting lockable attributes for .uasset or .umap at
Ok, I'll have a look. Thanks.

2025-01-18 18:42 UTC, sanxfxteam commented
Upgraded to an error.

2025-01-18 18:43 UTC, sanxfxteam commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					UE_LOG(LogSourceControl, Warning, TEXT("Git LFS Locking is disabled. Files .uasset or .umap are not lockable. Make sure your .gitattributes is setting lockable attributes for .uasset or .umap at
Upgraded to an error.

2025-01-18 20:26 UTC, mastercoms commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					|| !GitSourceControlUtils::IsFileLFSLockable(".uasset"))
The problem with this, is it will annoy people who wish to disable LFS locking, this should check if locking is even enabled in the first place by the user.

2025-01-18 22:26 UTC, sanxfxteam commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					|| !GitSourceControlUtils::IsFileLFSLockable(".uasset"))
I thought I already checked that, I will double check.

2025-01-20 02:50 UTC, sanxfxteam commented on Source/GitSourceControl/Private/GitSourceControlProvider.cpp
> +					|| !GitSourceControlUtils::IsFileLFSLockable(".uasset"))
Ok I've added the check for GitLFSLock. However I'm surprise when this function ```FGitSourceControlProvider::CheckRepositoryStatus()``` is called, it's called on the selection of the source control and not when doing apply settings.

2025-01-20 04:00 UTC, mastercoms approved these changes

2025-01-20 04:00 UTC, merged

2025-01-20 04:00 UTC, mastercoms commented
Awesome change, thanks so much for the contribution!