add additional whitelisting in .gitignore
ProjectBorealis/UE4GitPlugin pull request #76
Opened 2023-01-21 09:54 UTC by as3mbus

i am proposing this change to assist the installation process in project scope. 

especially when user trying to add ue git plugin inside the project to ease distribution.  since recommended `.gitignore` of pbcore ignores git-lfs.exe files which required by the plugin to works

2023-01-21 12:47 UTC, mastercoms requested changes
Thanks, great idea! Could you add it for the other executables as well?

2023-01-24 02:54 UTC, as3mbus commented
the other executable doesn't get ignored by pbcore .gitignore by default. or you'd say just add it to gitignore whitelist regardless the condition ?

2023-01-24 03:41 UTC, mastercoms commented
Some people use the Epic gitignore which ignores everything by default

2023-01-24 04:01 UTC, as3mbus commented
updated with all executables files

2023-01-24 04:23 UTC, mastercoms approved these changes

2023-01-24 04:23 UTC, merged